# Generated by Django 2.2.2 on 2019-06-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190620_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='pub_data',
        ),
    ]
