# Generated by Django 2.2.2 on 2019-06-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='headImage',
            field=models.FileField(default='./uploads/headImg.jpg', upload_to='./uploads'),
        ),
    ]
