# Generated by Django 2.2.2 on 2019-06-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('headImg', models.FileField(upload_to='./uploads')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='headImg',
            field=models.FileField(upload_to='./uploads', verbose_name='头像'),
        ),
    ]
