# Generated by Django 2.2.2 on 2019-06-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_myuser_headimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='headImage',
            field=models.FileField(default='./uploads/default/headImg.jpg', upload_to='./uploads'),
        ),
    ]
