# Generated by Django 2.2.2 on 2019-06-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190629_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='headImage',
        ),
        migrations.AddField(
            model_name='myuser',
            name='headImg',
            field=models.FileField(default='./uploads/default/headImg.jpg', upload_to='./uploads'),
        ),
    ]
