# Generated by Django 2.2.2 on 2019-06-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190629_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
    ]
