# Generated by Django 2.2.2 on 2019-07-04 17:40

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_dynamic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='context',
            field=models.CharField(max_length=254, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='img',
            field=models.FileField(upload_to=login.models.dynamic_upload_path),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='username',
            field=models.CharField(max_length=150, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='headImg',
            field=models.FileField(default='./uploads/default/headImg.jpg', upload_to=login.models.head_image_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='isOnline',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='用户名'),
        ),
    ]
